
name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Remove existing files but keep .git and .github
        find . -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'dist' -exec rm -rf {} + 2>/dev/null || true
        
        # Move built files to root
        mv dist/* . 2>/dev/null || true
        mv dist/.* . 2>/dev/null || true
        rmdir dist 2>/dev/null || true
        
        # Add and commit
        git add .
        git commit -m "Deploy to GitHub Pages" || exit 0
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
